In [12]:
import time
import datetime
import pandas as pd
import numpy as np
import datetime
import warnings
warnings.filterwarnings("ignore")
from matplotlib import pyplot
# Loading datasets
data = pd.read_csv("./Data/PM25.csv", na_values = "NaN",  parse_dates=['Date'], date_parser = pd.to_datetime )

In [13]:
# Replacing -1 values (which is missing values) to NaN
data.replace(-1, 'NaN', inplace=True)
data = data[(data != "NaN")]

In [14]:
#Dataset Data Types
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6580 entries, 0 to 6579
Data columns (total 20 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   Date                            6580 non-null   datetime64[ns]
 1   Source                          6580 non-null   object
 2   Site ID                         6580 non-null   int64
 3   POC                             6580 non-null   int64
 4   Daily Mean PM2.5 Concentration  6580 non-null   float64
 5   UNITS                           6580 non-null   object
 6   DAILY_AQI_VALUE                 6580 non-null   int64
 7   Site Name                       6580 non-null   object
 8   DAILY_OBS_COUNT                 6580 non-null   int64
 9   PERCENT_COMPLETE                6580 non-null   float64
 10  AQS_PARAMETER_CODE              6580 non-null   int64
 11  AQS_PARAMETER_DESC              6580 non-null   object
 12  CBSA_CODE                       6580 non-null   int64
 13  CBSA_NAME                       6580 non-null   object
 14  STATE_CODE                      6580 non-null   int64
 15  STATE                           6580 non-null   object
 16  COUNTY_CODE                     6580 non-null   int64
 17  COUNTY                          6580 non-null   object
 18  SITE_LATITUDE                   6580 non-null   float64
 19  SITE_LONGITUDE                  6580 non-null   float64
dtypes: datetime64[ns](1), float64(4), int64(8), object(7)
memory usage: 1.0+ MB

In [15]:
#Statistical data Description
data.describe()

,Site ID,POC,Daily Mean PM2.5 Concentration,DAILY_AQI_VALUE,DAILY_OBS_COUNT,PERCENT_COMPLETE,AQS_PARAMETER_CODE,CBSA_CODE,STATE_CODE,COUNTY_CODE,SITE_LATITUDE,SITE_LONGITUDE
count,6.580000e+03,6580.000000,6580.000000,6580.000000,6580.0,6580.0,6580.000000,6580.0,6580.000000,6580.000000,6580.000000,6580.000000
mean,1.940782e+08,2.548024,9.288419,37.017629,1.0,100.0,88202.651672,16980.0,19.336778,70.916413,41.819441,-87.757181
std,8.589406e+07,1.317267,4.758381,16.037528,0.0,0.0,174.453097,0.0,8.591361,49.299896,0.279151,0.310646
min,1.703100e+08,1.000000,-0.100000,0.000000,1.0,100.0,88101.000000,16980.0,17.000000,31.000000,41.221537,-88.329374
25%,1.703131e+08,1.000000,5.800000,24.000000,1.0,100.0,88101.000000,16980.0,17.000000,31.000000,41.606662,-87.876265
50%,1.704340e+08,3.000000,8.600000,36.000000,1.0,100.0,88101.000000,16980.0,17.000000,43.000000,41.771071,-87.748902
75%,1.808900e+08,3.000000,11.700000,49.000000,1.0,100.0,88502.000000,16980.0,18.000000,89.000000,41.965485,-87.495044
max,5.505900e+08,9.000000,74.000000,161.000000,1.0,100.0,88502.000000,16980.0,55.000000,197.000000,42.504722,-87.199167

In [16]:
#Describing Percentage for each column Total Missing Values in the Datasets
data.isnull().sum() * 100 / len(data)

Date                              0.0
Source                            0.0
Site ID                           0.0
POC                               0.0
Daily Mean PM2.5 Concentration    0.0
UNITS                             0.0
DAILY_AQI_VALUE                   0.0
Site Name                         0.0
DAILY_OBS_COUNT                   0.0
PERCENT_COMPLETE                  0.0
AQS_PARAMETER_CODE                0.0
AQS_PARAMETER_DESC                0.0
CBSA_CODE                         0.0
CBSA_NAME                         0.0
STATE_CODE                        0.0
STATE                             0.0
COUNTY_CODE                       0.0
COUNTY                            0.0
SITE_LATITUDE                     0.0
SITE_LONGITUDE                    0.0
dtype: float64

In [17]:
# Dataset shape with NaN Values
data.shape

(6580, 20)

In [18]:
# NaN Values Drop and Clean Dataset 
data = data.dropna()

In [19]:
# After removing NaN Values the Dateset shape
data.shape

(6580, 20)

In [20]:
#Extraction in the new column Year, Month, Day, Time from Date
data['Year'] = data.Date.dt.year.astype('int64')
data['Month'] = data.Date.dt.month.astype('int64')
data['Week'] = data.Date.dt.week.astype('int64')
data['Day'] = data.Date.dt.day.astype('int64')
# create a list of our conditions
conditions = [
    (data['DAILY_AQI_VALUE'] <= 50),
    (data['DAILY_AQI_VALUE'] > 50) & (data['DAILY_AQI_VALUE'] <= 100),
    (data['DAILY_AQI_VALUE'] > 100) & (data['DAILY_AQI_VALUE'] <= 150),
    (data['DAILY_AQI_VALUE'] > 151)
    ]

# create a list of the values we want to assign for each condition
values = ['1', '2', '3', '4']

# create a new column and use np.select to assign values to it using our lists as arguments
data['Level'] = np.select(conditions, values)

In [21]:
#Dataset
data

,Date,Source,Site ID,POC,Daily Mean PM2.5 Concentration,UNITS,DAILY_AQI_VALUE,Site Name,DAILY_OBS_COUNT,PERCENT_COMPLETE,...,STATE,COUNTY_CODE,COUNTY,SITE_LATITUDE,SITE_LONGITUDE,Year,Month,Week,Day,Level
0,2018-01-02,AQS,170310001,1,12.9,ug/m3 LC,53,VILLAGE GARAGE,1,100.0,...,Illinois,31,Cook,41.670992,-87.732457,2018,1,1,2,2
1,2018-01-08,AQS,170310001,1,14.7,ug/m3 LC,56,VILLAGE GARAGE,1,100.0,...,Illinois,31,Cook,41.670992,-87.732457,2018,1,2,8,2
2,2018-01-14,AQS,170310001,1,8.9,ug/m3 LC,37,VILLAGE GARAGE,1,100.0,...,Illinois,31,Cook,41.670992,-87.732457,2018,1,2,14,1
3,2018-01-20,AQS,170310001,1,11.7,ug/m3 LC,49,VILLAGE GARAGE,1,100.0,...,Illinois,31,Cook,41.670992,-87.732457,2018,1,3,20,1
4,2018-01-26,AQS,170310001,1,6.0,ug/m3 LC,25,VILLAGE GARAGE,1,100.0,...,Illinois,31,Cook,41.670992,-87.732457,2018,1,4,26,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6575,2018-12-27,AQS,550590019,3,9.9,ug/m3 LC,41,CHIWAUKEE PRAIRIE STATELINE,1,100.0,...,Wisconsin,59,Kenosha,42.504722,-87.809300,2018,12,52,27,1
6576,2018-12-28,AQS,550590019,3,3.9,ug/m3 LC,16,CHIWAUKEE PRAIRIE STATELINE,1,100.0,...,Wisconsin,59,Kenosha,42.504722,-87.809300,2018,12,52,28,1
6577,2018-12-29,AQS,550590019,3,5.6,ug/m3 LC,23,CHIWAUKEE PRAIRIE STATELINE,1,100.0,...,Wisconsin,59,Kenosha,42.504722,-87.809300,2018,12,52,29,1
6578,2018-12-30,AQS,550590019,3,8.8,ug/m3 LC,37,CHIWAUKEE PRAIRIE STATELINE,1,100.0,...,Wisconsin,59,Kenosha,42.504722,-87.809300,2018,12,52,30,1
6579,2018-12-31,AQS,550590019,3,8.8,ug/m3 LC,37,CHIWAUKEE PRAIRIE STATELINE,1,100.0,...,Wisconsin,59,Kenosha,42.504722,-87.809300,2018,12,1,31,1

In [22]:
# Spliting dataset for training data and for testing data
from sklearn.model_selection import train_test_split
# Classifier Algorithm libraries loading

from sklearn.neural_network import MLPClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.linear_model import LogisticRegression
#Import scikit-learn metrics module for accuracy calculation
from sklearn import metrics
# Features
f = data[['SITE_LATITUDE','SITE_LONGITUDE','COUNTY_CODE','Month','Week','Day']]
# Lables
l = data['Level']
# Spliting 30% data for test and 70% data fro Training
x_train, x_test, y_train, y_test = train_test_split(f, l, test_size=0.3,random_state=42)
# Evaluate Algorithms on default parameters
models = []
models.append(('(Multi-layer Perceptron)', MLPClassifier()))
models.append(('(K-nearest Neighbors)', KNeighborsClassifier()))
models.append(('(Naive Bayes)', GaussianNB()))
models.append(('(Logistic Regression)', LogisticRegression()))

for name, model in models:
    print("Model: ",name)
    # Execution time is calculating for each model accuracy
    start = time.time()
    # model fit for traning and prediction
    model.fit(x_train, y_train)
    y_pred = model.predict(x_test)
    # Accuracy Score
    print("Accuracy:", metrics.accuracy_score(y_test, y_pred))
    stop = time.time()
    print("Execution Time: ",stop-start)
    print("\n")
    print('F1:', metrics.f1_score(y_test, y_pred,average='micro'))
    print('Precision:', metrics.precision_score(y_test, y_pred,average='micro'))
    print('Recall:', metrics.recall_score(y_test, y_pred,average='micro'))
    print("\n")
    print("\n#######################################\n")

Model:  (Multi-layer Perceptron)
Accuracy: 0.767983789260385
Execution Time:  1.2378504276275635


F1: 0.767983789260385
Precision: 0.767983789260385
Recall: 0.767983789260385



#######################################

Model:  (K-nearest Neighbors)
Accuracy: 0.8500506585612969
Execution Time:  0.11496329307556152


F1: 0.8500506585612969
Precision: 0.8500506585612969
Recall: 0.8500506585612969



#######################################

Model:  (Naive Bayes)
Accuracy: 0.7801418439716312
Execution Time:  0.01899266242980957


F1: 0.7801418439716311
Precision: 0.7801418439716312
Recall: 0.7801418439716312



#######################################

Model:  (Logistic Regression)
Accuracy: 0.7695035460992907
Execution Time:  0.2909066677093506


F1: 0.7695035460992907
Precision: 0.7695035460992907
Recall: 0.7695035460992907



#######################################